export const throwSampleError = (): void => {
  throw new Error('sample not found')
}
